### ISSUE TITLE
Test con LiveCharts

### ISSUE THREAD

**Issue by cala-br** [mmr-driverless/Mmr.Telemetry#6]
Creare un branch `charts` partendo dal branch `ui`

Nell'app Maui crea una pagina `ChartTests` in cui inserire il grafico di `LiveCharts`

Farei come test iniziale uno molto banale, quindi grafico a tutto schermo + dati inseriti in maniera statica, giusto per vedere se la libreria effettivamente funziona, quanti punti regge ecc...

E.g (a mente)
```cs
Enumerable
    .Range(0, qualcheCentinaiaDiMigliaia)
    .Select(n => new Reading
    {
        Value = n * 10,
        Timestamp = DateTime.UtcNow + TimeSpan.FromSeconds(n),
    });
```

**Comment by Shibodd** [comment]
Solo la versione v2, che e' in beta, ha il supporto a Maui.
Non sono riuscito a fare partire lo zoom su Maui e lo scroll funziona malissimo, sia su Android che Windows, mentre lo stesso identico codice funziona normalmente su WPF.  Ho provato su 3 diverse versioni, 2.0.0-beta 514/500/401.
Non sembrano esserci serie ottimizzate per dati ordinati (e.g. time-series). Devo provare a vedere se si riescono a implementare - a prima occhiata sembra non facilmente.
Su un Ryzen 5 3600, a qualsiasi livello di zoom, con >70k punti in qualsiasi disposizione (pure una retta orizzontale) ci mette quasi mezzo secondo per reagire alle interazioni.
Sull'emulatore android con la meta' dei punti e' gia' inutilizzabile.

Pusho, sarebbe comodo ottenere un feedback se si comporta cosi' solo sulla mia macchina.

-- edit, non ho i permessi per pushare.

**Comment by cala-br** [comment]
@Shibodd Te li do subito
